export const ACCESS_TYPES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  RESOURCE_MANAGER: 'RESOURCE_MANAGER',
  CONFLICT_MANAGER: 'CONFLICT_MANAGER',
  GENERAL_USER: 'GENERAL_USER'
};
